<template>
  <div class="shell">
    <aside><h1>知识资产</h1><p class="muted">企业文档协作平台</p><button v-for="item in nav" :key="item.key" :class="{active: tab===item.key}" @click="tab=item.key">{{ item.label }}</button></aside>
    <main>
      <header><div><h2>{{ title }}</h2><span class="muted">{{ user || "未登录" }}</span></div><button v-if="user" class="ghost" @click="logout">退出</button></header>
      <section v-if="!user" class="login card"><h2>登录平台</h2><input v-model="email" placeholder="企业邮箱"><input v-model="password" type="password" placeholder="密码"><button class="primary" @click="doLogin">登录</button><p v-if="error" class="error">{{ error }}</p></section>
      <template v-else>
        <section v-if="tab==='dashboard'" class="grid"><div class="card metric"><span>知识空间</span><b>{{ spaces.length }}</b></div><div class="card metric"><span>当前文档</span><b>{{ docs.length }}</b></div><div class="card metric"><span>已发布</span><b>{{ publishedCount }}</b></div><div class="card metric"><span>评论</span><b>{{ reportData?.comments ?? 0 }}</b></div><div class="card wide"><h3>工作空间</h3><select v-model="workspaceId" @change="loadDocs"><option v-for="s in spaces" :value="s.id">{{ s.name }}</option></select><button class="primary small" @click="newSpace">新建空间</button></div></section>
        <section v-if="tab==='documents'" class="card"><div class="toolbar"><input v-model="query" placeholder="搜索标题、摘要或正文" @keyup.enter="loadDocs"><button class="primary" @click="newDoc">新建文档</button></div><div class="doc" v-for="doc in docs" :key="doc.id" @click="openDoc(doc.id)"><div><b>{{ doc.title }}</b><p>{{ doc.summary || '暂无摘要' }}</p></div><span :class="['status',doc.status]">{{ doc.status }}</span></div></section>
        <section v-if="tab==='editor'" class="card editor"><div v-if="current"><input class="title" v-model="current.title"><textarea v-model="current.body" rows="18"></textarea><div class="toolbar"><button class="primary" @click="save">保存草稿</button><button @click="publish">发布版本</button><span class="muted">版本 {{ current.version }} · {{ savedAt }}</span></div><h3>评论</h3><div v-for="c in currentComments" :key="c.id" class="comment"><b>{{ c.author_id }}</b><span>{{ c.body }}</span></div><input v-model="commentText" placeholder="写下评论" @keyup.enter="comment"><p v-if="error" class="error">{{ error }}</p></div><p v-else class="muted">请从文档列表打开文档。</p></section>
        <section v-if="tab==='search'" class="card"><div class="toolbar"><input v-model="searchText" placeholder="全文搜索" @keyup.enter="doSearch"><button class="primary" @click="doSearch">搜索</button></div><div class="doc" v-for="item in searchResults" :key="item.document.id" @click="openDoc(item.document.id)"><b>{{ item.document.title }}</b><span>{{ item.highlight }}</span></div></section>
        <section v-if="tab==='recycle'" class="card"><h3>回收站</h3><div class="doc" v-for="item in recycleItems" :key="item.id"><span>{{ item.name }}</span><button @click="restore(item.id)">恢复</button></div></section>
        <section v-if="tab==='report'" class="grid"><div class="card metric"><span>文档总数</span><b>{{ reportData?.documents ?? 0 }}</b></div><div class="card metric"><span>发布数量</span><b>{{ reportData?.published ?? 0 }}</b></div><div class="card metric"><span>阅读次数</span><b>{{ reportData?.reads ?? 0 }}</b></div><div class="card metric"><span>附件数量</span><b>{{ reportData?.attachments ?? 0 }}</b></div></section>
      </template>
    </main>
  </div>
</template>
<script setup lang="ts">
import { computed, onMounted, ref } from "vue"
import { login, workspaces, documents, createWorkspace, createDocument, saveDraft, documentDetail, comments, addComment, search, recycle, report } from "./api"
const nav=[{key:"dashboard",label:"数据看板"},{key:"documents",label:"文档库"},{key:"editor",label:"在线编辑"},{key:"search",label:"全文搜索"},{key:"recycle",label:"回收站"},{key:"report",label:"统计报表"}]
const tab=ref("dashboard"),email=ref("owner@example.com"),password=ref("secret"),user=ref(localStorage.getItem("kac_access_token")?email.value:"")
const error=ref(""),spaces=ref<any[]>([]),docs=ref<any[]>([]),workspaceId=ref(""),query=ref(""),current=ref<any>(null),currentComments=ref<any[]>([]),commentText=ref(""),savedAt=ref("未保存"),searchText=ref(""),searchResults=ref<any[]>([]),recycleItems=ref<any[]>([]),reportData=ref<any>(null)
const title=computed(()=>nav.find(x=>x.key===tab.value)?.label||""); const publishedCount=computed(()=>docs.value.filter(x=>x.status==='published').length)
async function load(){ try{spaces.value=await workspaces();workspaceId.value=spaces.value[0]?.id||"";if(workspaceId.value){await loadDocs();reportData.value=await report(workspaceId.value)};recycleItems.value=await recycle()}catch(e:any){error.value=e?.response?.data?.error?.message||e.message} }
async function doLogin(){try{await login(email.value,password.value);user.value=email.value;await load()}catch(e:any){error.value=e?.response?.data?.error?.message||"登录失败"}}
function logout(){localStorage.removeItem("kac_access_token");user.value=""}
async function loadDocs(){if(workspaceId.value)docs.value=await documents(workspaceId.value,query.value)}
async function newSpace(){const name=window.prompt("空间名称");if(name){await createWorkspace({name,visibility:"organization"});await load()}}
async function newDoc(){if(!workspaceId.value)return;const d=await createDocument({workspace_id:workspaceId.value,title:"新建知识文档",summary:"",body:"开始记录企业知识…"});await loadDocs();await openDoc(d.id)}
async function openDoc(id:string){current.value=await documentDetail(id);currentComments.value=await comments(id);tab.value="editor"}
async function save(){if(!current.value)return;try{current.value=await saveDraft(current.value.id,current.value.body,current.value.version);savedAt.value=new Date().toLocaleTimeString()}catch(e:any){error.value=e?.response?.data?.error?.message||e.message}}
async function publish(){if(!current.value)return;await save();await fetch(`/api/v1/documents/${current.value.id}/status`,{method:"PATCH",headers:{"Content-Type":"application/json",Authorization:`Bearer ${localStorage.getItem("kac_access_token")}`},body:JSON.stringify({status:"published"})});await loadDocs()}
async function comment(){if(current.value&&commentText.value){await addComment(current.value.id,commentText.value);commentText.value="";currentComments.value=await comments(current.value.id)}}
async function doSearch(){searchResults.value=await search(searchText.value)}
async function restore(id:string){await fetch(`/api/v1/recycle-bin/${id}`,{method:"POST",headers:{Authorization:`Bearer ${localStorage.getItem("kac_access_token")}`}});recycleItems.value=await recycle();await loadDocs()}
onMounted(()=>{if(user.value)load()})
</script>
<style>
:root{font-family:Inter,"Microsoft YaHei",sans-serif;color:#172033;background:#f4f7fb}*{box-sizing:border-box}body{margin:0}.shell{display:flex;min-height:100vh}aside{width:230px;background:#12233f;color:white;padding:28px 18px}aside h1{margin:0;font-size:24px}aside button{display:block;width:100%;border:0;background:transparent;color:#d9e2f2;text-align:left;padding:13px 14px;margin:7px 0;border-radius:8px;cursor:pointer}aside button.active,aside button:hover{background:#2d63c8;color:white}main{flex:1;padding:30px 42px;max-width:1400px}header{display:flex;justify-content:space-between;align-items:center;margin-bottom:24px}.muted{color:#718096}.card{background:white;border:1px solid #e5ebf3;border-radius:14px;padding:24px;box-shadow:0 5px 18px #1720330b}.grid{display:grid;grid-template-columns:repeat(4,1fr);gap:18px}.wide{grid-column:span 4}.metric{display:flex;flex-direction:column;gap:12px}.metric b{font-size:32px;color:#2d63c8}.toolbar{display:flex;gap:12px;margin-bottom:18px}.toolbar input,.login input,select,.title,textarea{border:1px solid #d8e0ec;border-radius:8px;padding:11px;font:inherit}.toolbar input{flex:1}.primary{background:#2d63c8;color:#fff;border:0;border-radius:8px;padding:11px 18px;cursor:pointer}.small{margin-left:12px}.ghost{background:transparent;border:1px solid #c9d4e4;border-radius:8px;padding:8px 14px}.doc{display:flex;justify-content:space-between;align-items:center;padding:17px 8px;border-bottom:1px solid #edf1f7;cursor:pointer}.doc p{margin:6px 0 0;color:#748094}.status{font-size:12px;padding:5px 9px;border-radius:14px;background:#edf2f7}.published{background:#dcfce7;color:#166534}.editor .title{width:100%;font-size:22px;margin-bottom:15px}.editor textarea{width:100%;resize:vertical;line-height:1.7}.comment{padding:10px 0;border-bottom:1px solid #edf1f7;display:flex;gap:12px}.login{max-width:420px;margin:80px auto;display:flex;flex-direction:column;gap:14px}.error{color:#d14343}@media(max-width:900px){aside{width:170px}main{padding:20px}.grid{grid-template-columns:repeat(2,1fr)}.wide{grid-column:span 2}}
</style>
